### ISSUE TITLE
No upload

### ISSUE THREAD

**Issue by hadim** [conda-forge/scijava-jupyter-kernel-feedstock#4]
Something is wrong and the package is not uploaded. See the circleci build for example https://circleci.com/gh/conda-forge/scijava-jupyter-kernel-feedstock/1?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Could you have a look @ocefpaf ?

**Comment by ocefpaf** [comment]
> Could you have a look @ocefpaf ?

I re-started the CI. Fingers crossed.

**Comment by hadim** [comment]
Same error : 

```
INFO conda_build.build:bundle_conda(865): Packaging scijava-jupyter-kernel-0.2.1-0
number of files: 103
Fixing permissions
Fixing permissions
/feedstock_root/build_artefacts/linux-64/scijava-jupyter-kernel-0.2.1-0.tar.bz2
Nothing to test for: /feedstock_root/build_artefacts/linux-64/scijava-jupyter-kernel-0.2.1-0.tar.bz2
INFO conda_build.config:__exit__(432): --dirty flag not specified.  Removing build folder after successful build/test.

# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /feedstock_root/build_artefacts/linux-64/scijava-jupyter-kernel-0.2.1-0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
+ test -f /home/ubuntu/scijava-jupyter-kernel-feedstock/build_artefacts/conda-forge-build-done
+ exit 1

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by ocefpaf** [comment]
I will take a closer look tomorrow. (I am tired and out of ideas today :smile:)

**Comment by hadim** [comment]
Looks like the missing test was the cause of the issue. Should be resolved now with #5.

**Comment by hadim** [comment]
I give up... I tried everything... I don't know what is happening...

**Comment by hadim** [comment]
See #5 if you want to have a look.

**Comment by hadim** [comment]
Working on master now since I try to get the packages to be uploaded.

**Comment by ocefpaf** [comment]
@hadim I had a smiliar issue with `nco` and I remember other people mentioning that they also had that problem in other feedstocks.

In the `nco` case it was a single test command that prevented the package from being uploaded. See https://github.com/conda-forge/nco-feedstock/blob/master/recipe/run_test.sh#L14

I guess you will beed to debug line by line to find if that is happening here too :unamused:

**Comment by hadim** [comment]
Thanks. I'll have a look.

**Comment by hadim** [comment]
I am very confused, this call is not even called by CircleCI since it's executed on Darwin system (or am i missing something ?).

```
if [[ $(uname) == Darwin ]]; then
```

**Comment by ocefpaf** [comment]
You are talking about the `nco` feedstock? Yes, I had to prevent that line from running on CircleCI. That is the "fixed" version.

**Comment by hadim** [comment]
oh I see.

**Comment by hadim** [comment]
Is there is a way for you to check the BIN_TOKEN value is correct ?

**Comment by hadim** [comment]
I think I got it. CircleCi doesn't like `./gradlew` I had to use `./gradlew --no-daemon` instead. 

Fingers crossed : https://circleci.com/gh/conda-forge/scijava-jupyter-kernel-feedstock/48?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hadim** [comment]
It worked.

**Comment by hadim** [comment]
Last thing @ocefpaf and then I should be good.

Could you remove the packages from https://anaconda.org/conda-forge/scijava-jupyter-kernel/files ?

Remove everything below 0.2.2-3.

The first version are often broken and some get selected by conda to be installed because of some conflicts...

**Comment by hadim** [comment]
If you give me access to this repo, I can take care of it, if you prefer.

**Comment by ocefpaf** [comment]
> If you give me access to this repo

You have access to this repo. I believe you mean the channel? That we cannot do because anaconda.org has no granularity to grant access to each package.

> Remove everything below 0.2.2-3.

I am confused. By below do you mean version/build number lower than that? That seems to be everything.

**Comment by hadim** [comment]
Sorry I mean the channel yes.

Everything below 0.2.2-3 (not included) : three packages should remain.

**Comment by ocefpaf** [comment]
Done. Can you check if that is correct?

**Comment by hadim** [comment]
Perfect ! Thanks for all the help.
